nys_unav.settings:
  type: mapping
  label: 'NYS uNav'
  mapping:
    nys_unav:
      type: mapping
      mapping:
        nys_unav_auto:
          type: text
          label: 'uNav automatic insertion'
        nys_unav_interactive:
          type: text
          label: 'uNav interactive'